/*
ATTENTION READ THIS FIRST

PROBLEMS:
MESSAGING DOES NOT WORK WITHOUT THE CODE IN CHAT... TEST COMPONENT HOLDS MAJOR CODE FOR MESSAGING BUT NEEDS SOMETHING IN CHAT COMPONENT


https://docs.google.com/document/d/1tLloz9y-T9lLBnPGbRdpfilCRMlqMBYWriB5resdGRk/edit


*/
